version: "3"
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api